### ISSUE TITLE
no issues here

### ISSUE THREAD

**Issue by D4iviz** [aquajay2022/Remote-Access-software-little-project#1]
God damn man, if you are gonna jump me with a knife in the middle of London and take my wallet then at least run away without dropping your own, not only did you only have 5 pounds in your wallet which is I assume why you stole mine, you also had your business card in it with your GitHub page. I know that programming doesn't pay but be like the others and get a job at burger king instead. Terrible code anyway skill issue.
![Screenshot_20230423-212232~2](https://user-images.githubusercontent.com/127542994/234188688-c0be22ed-ea07-4442-a8d6-174766f21b21.png)

**Comment by aquajay2022** [comment]
Simply false
